- hosts: local
  become: 
    true
  become_method: 
    sudo

  handlers:
    - name: update packages
      apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 86400
  
  tasks:
    - name: Update packages 
      shell: echo "Updating..."
      notify:
        - update packages
      tags: update

    - name: Install packages to allow apt to use a repository over HTTPS
      apt: 
        name: "{{item}}"
        state: latest
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Add Docker’s official GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      args:
        executable: /bin/bash

    - name: Fingerprint verify
      shell: apt-key fingerprint 0EBFCD88
      args:
        executable: /bin/bash
      notify:
        - update packages

    - name: Install the latest version of Docker CE
      apt:
        name: "{{items}}"
        state: latest
      with_items: 
        - docker-ce
        - docker-ce-cli
        - containerd.io 
